export default {
  login: "ryanbourdais",
  id: 67397011,
  node_id: "MDQ6VXNlcjY3Mzk3MDEx",
  avatar_url: "https://avatars.githubusercontent.com/u/67397011?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ryanbourdais",
  html_url: "https://github.com/ryanbourdais",
  followers_url: "https://api.github.com/users/ryanbourdais/followers",
  following_url:
    "https://api.github.com/users/ryanbourdais/following{/other_user}",
  gists_url: "https://api.github.com/users/ryanbourdais/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/ryanbourdais/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ryanbourdais/subscriptions",
  organizations_url: "https://api.github.com/users/ryanbourdais/orgs",
  repos_url: "https://api.github.com/users/ryanbourdais/repos",
  events_url: "https://api.github.com/users/ryanbourdais/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/ryanbourdais/received_events",
  type: "User",
  site_admin: false,
  name: "Ryan Bourdais",
  company: "Crimer inc",
  blog: "ryanbourdais.com",
  location: "Baton Rouge, LA",
  email: null,
  hireable: null,
  bio: "Software Engineer",
  twitter_username: "RyanBourdais",
  public_repos: 12,
  public_gists: 0,
  followers: 0,
  following: 2,
  created_at: "2020-06-24T23:13:52Z",
  updated_at: "2021-12-23T15:39:38Z",
};
